CREATE TABLE IF NOT EXISTS giveaways (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dag TINYINT NOT NULL,
    maand TINYINT NOT NULL,
    jaar SMALLINT NOT NULL,
    tijd VARCHAR(5) NOT NULL,
    aantal_winnaars TINYINT NOT NULL,
    prijs VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);